spring:
  application:
    name: e-commerce-batch
  datasource:
    url: jdbc:postgresql://localhost:15432/ecb?profileSQL=true
    username: postgres
    password:
    hikari:
      maximum-pool-size: 200
  batch:
    jdbc:
      initialize-schema: always
logging:
  level:
    root: INFO
    org.springframework.jdbc.core.jdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: DEBUG
prometheus:
  job:
    name: spring-batch
  push-gate-way:
    address: 'localhost:19091'
