spring:
  application:
    name: e-commerce-batch
  datasource:
    url: jdbc:postgresql://localhost:15432/ecb?profileSQL=true&reWriteBatchedInserts=true
    username: postgres
    password:
    hikari:
      maximum-pool-size: 32
  batch:
    jdbc:
      initialize-schema: always
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
        order_updates: true
        order_insert: true
logging:
  level:
    root: INFO
#    org.springframework.jdbc.core.jdbcTemplate: DEBUG
#    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
prometheus:
  job:
    name: spring-batch
  push-gate-way:
    address: 'localhost:19091'
