services:
  postgres:
    image: postgres:16
    container_name: ecb-postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - '15432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=local
    restart: always